// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pos_to_transactions_ternary_cpp
Rcpp::DataFrame pos_to_transactions_ternary_cpp(const Rcpp::CharacterVector& datetime, const Rcpp::NumericVector& open, const Rcpp::NumericVector& close, const Rcpp::IntegerVector& pos, const std::string mode);
RcppExport SEXP _investlabr_pos_to_transactions_ternary_cpp(SEXP datetimeSEXP, SEXP openSEXP, SEXP closeSEXP, SEXP posSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type datetime(datetimeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type open(openSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type close(closeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pos(posSEXP);
    Rcpp::traits::input_parameter< const std::string >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(pos_to_transactions_ternary_cpp(datetime, open, close, pos, mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_investlabr_pos_to_transactions_ternary_cpp", (DL_FUNC) &_investlabr_pos_to_transactions_ternary_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_investlabr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
