# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pos_to_transactions_ternary_cpp <- function(datetime, open, close, pos, mode = "new_open") {
    .Call(`_investlabr_pos_to_transactions_ternary_cpp`, datetime, open, close, pos, mode)
}

